"""empty message

Revision ID: ecd78292a5ba
Revises: d816dc5aff65
Create Date: 2022-08-14 10:45:57.213488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd78292a5ba'
down_revision = 'd816dc5aff65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('want_venue', sa.Boolean(), nullable=True))
    op.add_column('artists', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'description')
    op.drop_column('artists', 'want_venue')
    # ### end Alembic commands ###
